/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsProfileImport } from './routes/settings/profile'
import { Route as CarCarIdImport } from './routes/car/$carId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsProfileRoute = SettingsProfileImport.update({
  path: '/settings/profile',
  getParentRoute: () => rootRoute,
} as any)

const CarCarIdRoute = CarCarIdImport.update({
  path: '/car/$carId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/car/$carId': {
      id: '/car/$carId'
      path: '/car/$carId'
      fullPath: '/car/$carId'
      preLoaderRoute: typeof CarCarIdImport
      parentRoute: typeof rootRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/car/$carId': typeof CarCarIdRoute
  '/settings/profile': typeof SettingsProfileRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/car/$carId': typeof CarCarIdRoute
  '/settings/profile': typeof SettingsProfileRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/car/$carId': typeof CarCarIdRoute
  '/settings/profile': typeof SettingsProfileRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/car/$carId' | '/settings/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/car/$carId' | '/settings/profile'
  id: '__root__' | '/' | '/car/$carId' | '/settings/profile'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarCarIdRoute: typeof CarCarIdRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarCarIdRoute: CarCarIdRoute,
  SettingsProfileRoute: SettingsProfileRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/car/$carId",
        "/settings/profile"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/car/$carId": {
      "filePath": "car/$carId.tsx"
    },
    "/settings/profile": {
      "filePath": "settings/profile.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
