services:
  postgres:
    image: postgres:latest
    container_name: postgres_server
    environment:
      - POSTGRES_USER=${USER_NAME}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - "5432:${PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
